# Generated by Django 2.2.24 on 2023-02-21 11:12

from django.db import migrations




class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_owner_pure_phone'),
    ]

    operations = [
        #
    ]

