# Generated by Django 2.2.24 on 2023-02-21 11:22

from django.db import migrations

from phonenumbers import NumberParseException
from phonenumbers import parse, is_valid_number


def parse_phone_number(value):
    try:
        phone = parse(value, 'RU')
        if not is_valid_number(phone):
            raise NumberParseException(phone, '')
        return phone
    except NumberParseException:
        return None


def set_owner_pure_phone(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat') # noqa
    for flat in Flat.objects.all().iterator():
        flat.owner_pure_phone = parse_phone_number(flat.owners_phonenumber)
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20230221_1422'),
    ]

    operations = [
        migrations.RunPython(set_owner_pure_phone),
    ]
