# Generated by Django 2.2.24 on 2023-02-21 11:54

from django.db import migrations

def create_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')  # noqa
    Owner = apps.get_model('property', 'Owner')  # noqa

    for flat in Flat.objects.all().iterator():
        owner = flat.owner
        owners_phonenumber = flat.owners_phonenumber
        owner_pure_phone = flat.owner_pure_phone
        owner, _ = Owner.objects.get_or_create(
            name=owner,
            owners_phonenumber=owners_phonenumber,
            owner_pure_phone=owner_pure_phone,
        )

        flat.owners.set([owner])

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20230221_1454'),
    ]

    operations = [
        migrations.RunPython(create_owners),
    ]
